export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_STATE = "LOGIN_STATE";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_NEW_USER_SUCCESS = "REGISTER_NEW_USER_SUCCESS";
export const REGISTER_NEW_USER_FAILED = "REGISTER_NEW_USER_FAILED";
export const LOADING_STATE = "LOADING_STATE";

export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILED = "CHECK_EMAIL_FAILED";
export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST"

export const INIT_LOGIN_USER= "INIT_LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SHOW_TOAST = "SHOW_TOAST";
export const SHOW_AUTH_TOAST = "SHOW_AUTH_TOAST";

export const REQUEST_OTP_SUCCESS = "REQUEST_OTP_SUCCESS";
export const REQUEST_OTP_FAILED = "REQUEST_OTP_FAILED";
export const REQUEST_OTP_LOADING = "REQUEST_OTP_LOADING";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";
export const VERIFY_OTP_LOADING = "VERIFY_OTP_LOADING";