export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_STATE = "LOGIN_STATE";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_NEW_USER_SUCCESS = "REGISTER_NEW_USER_SUCCESS";
export const REGISTER_NEW_USER_FAILED = "REGISTER_NEW_USER_FAILED";
export const LOADING_STATE = "LOADING_STATE";
export const INIT_LOADING_STATE = "INIT_LOADING_STATE";

export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILED = "CHECK_EMAIL_FAILED";
export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST";

export const NAVIGATE_TO_VERIFY_OTP_SCREEN = "NAVIGATE_TO_VERIFY_OTP_SCREEN";
export const NAVIGATE_TO_COMPLETE_REGISTRATION_SCREEN = "NAVIGATE_TO_COMPLETE_REGISTRATION_SCREEN";
export const NAVIGATE_TO_LOGIN_SCREEN = "NAVIGATE_TO_LOGIN_SCREEN";

export const INIT_LOGIN_USER= "INIT_LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SCREEN = "LOGOUT_USER_SCREEN";

export const SHOW_TOAST = "SHOW_TOAST";
export const SHOW_AUTH_TOAST = "SHOW_AUTH_TOAST";

export const REQUEST_OTP_SUCCESS = "REQUEST_OTP_SUCCESS";
export const REQUEST_OTP_FAILED = "REQUEST_OTP_FAILED";
export const REQUEST_OTP_LOADING = "REQUEST_OTP_LOADING";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";
export const VERIFY_OTP_LOADING = "VERIFY_OTP_LOADING";

export const REQUEST_TO_LEFT_VILLAGE_SUCCESS = "REQUEST_TO_LEFT_VILLAGE_SUCCESS";
export const REQUEST_TO_LEFT_VILLAGE_FAILED = "REQUEST_TO_LEFT_VILLAGE_FAILED";
export const SHOW_DISPLACEMENT_TOAST = "SHOW_DISPLACEMENT_TOAST";

export const GET_LEFT_AND_JOIN_VILLAGE_HISTORY_SUCCESS = "GET_LEFT_AND_JOIN_VILLAGE_HISTORY_SUCCESS";
export const GET_LEFT_AND_JOIN_VILLAGE_HISTORY_FAILED = "GET_LEFT_AND_JOIN_VILLAGE_HISTORY_FAILED";

export const APPROVE_CITIZEN_ADDRESS_SUCCESS = "APPROVE_CITIZEN_ADDRESS_SUCCESS";
export const APPROVE_CITIZEN_ADDRESS_FAILED = "APPROVE_CITIZEN_ADDRESS_FAILED";

export const APPROVE_LEAVE_AND_JOIN_SUCCESS = "APPROVE_LEAVE_AND_JOIN_SUCCESS";
export const APPROVE_LEAVE_AND_JOIN_FAILED = "APPROVE_LEAVE_AND_JOIN_FAILED";


export const FETCH_ALL_VILLAGE_CITIZENS_FAILED = "FETCH_ALL_VILLAGE_CITIZENS_FAILED";
export const FETCH_ALL_VILLAGE_CITIZENS__SUCCESS = "FETCH_ALL_VILLAGE_CITIZENS__SUCCESS";
export const NAVIGATE_TO_CITIZENS_SCREEN = "NAVIGATE_TO_CITIZENS_SCREEN";
export const SHOW_ADMIN_TOAST = "SHOW_ADMIN_TOAST";

export const APPOINT_LEADER_SUCCESS = "APPOINT_LEADER_SUCCESS";
export const APPOINT_LEADER_FAILED = "APPOINT_LEADER_FAILED";
export const DISAPPOINT_LEADER_SUCCESS = "DISAPPOINT_LEADER_SUCCESS";
export const DISAPPOINT_LEADER_FAILED = "DISAPPOINT_LEADER_FAILED";

export const SHOW_LEADER_TOAST = "SHOW_LEADER_TOAST";
export const FETCH_CITIZENS_REQUESTS_SUCCESS = "FETCH_CITIZENS_REQUESTS_SUCCESS";
export const FETCH_CITIZENS_REQUESTS_FAILED = "FETCH_CITIZENS_REQUESTS_FAILED";

export const ACKNOWLEDGE_CITIZEN_SUCCESS = "ACKNOWLEDGE_CITIZEN_SUCCESS";
export const ACKNOWLEDGE_CITIZEN_FAILED = "ACKNOWLEDGE_CITIZEN_FAILED";
